name: CI for Financial Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        
        with:
          python-version: '3.8'

      - name: Run Pipeline Script
        run: python pipeline.py

      - name: Set up Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "${{ secrets.ACCESS_TOKEN }}" | git credential approve
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/MouryaNaru18/financial-data-pipeline.git

      - name: Commit and Push Updated CSV
        run: |
          git add MRVL_data.csv
          git commit -m "Update CSV with new data"
          git push origin main
