name: CI for Financial Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pipeline Script
        run: python pipeline.py

      # Add a step to commit and push the updated CSV file
      - name: Commit and Push Updated CSV
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add MRVL_data.csv
          git commit -m "Update CSV with new data"
          git push origin main
