name: CI/CD for Financial Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pipeline Script
      run: python pipeline.py

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This uses the secret stored in your repository
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add MRVL_data.csv
        git commit -m "Update CSV with new data"
        git push origin main
